<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <PlatformTarget>x64</PlatformTarget>
        <AssemblyName>CMS21_Together_Server</AssemblyName>
        <RootNamespace>CMS21_Together_Server</RootNamespace>
        <LangVersion>latest</LangVersion>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="Facepunch.Steamworks.Win64">
          <HintPath>..\CMS21-Together-Core\Libs\Facepunch.Steamworks.Win64.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json">
          <HintPath>..\CMS21-Together-Core\Libs\Newtonsoft.Json.dll</HintPath>
        </Reference>
        <Reference Include="Terminal.Gui">
            <HintPath>Libs\TerminalGui\Terminal.Gui.dll</HintPath>
        </Reference>
        <Reference Include="NStack">
            <HintPath>Libs\TerminalGui\NStack.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
      <Content Include="Database\garage_upgrade_database.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="Database\item_database.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Include="Database\player_upgrade_database.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CMS21-Together-Core\CMS21-Together-Core.csproj" />
    </ItemGroup>
</Project>
